### ISSUE TITLE
Can't build distributable

### ISSUE THREAD

**Issue by tygriffin** [getoutreach/epf#143]
Following the instructions on the README I'm trying to build a browser distributable.
`ember-script build-browser` gives me this error:

```
fs.js:689
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'build-browser'
    at Object.fs.statSync (fs.js:689:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-script/lib/cli.js:124:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-script/bin/ember-script:3:1)
    at Module._compile (module.js:456:26)
```

I've got ember-script installed globally

**Comment by tygriffin** [comment]
I guess this is no longer the way to build a distributable. It works in previous versions, but now the build-browser file is gone from master. I ended up just grabbing a browser ready file with bower: `"epf": "getoutreach/epf-shim#0.3.5"`

**Comment by ghempton** [comment]
Yeah I recommend using the Bower shim. If you do want to build, however, you can do it with `npm run-script build`
