### ISSUE TITLE
api documentation

### ISSUE THREAD

**Issue by espretto** [getoutreach/epf#145]
i know there are a [couple](https://github.com/kiwiupover/epf_example) of [example](https://github.com/opsb/ember-cli-epf-todos) implementations using epf but i'd still really like to see some api documentation. i'm quite familiar with ember and it's architecture so i find the hooks and methods in the source but that's not how it should be. i assume you're using [NaturalDocs](http://www.naturaldocs.org/)-like comments in your code. if you could just generate the docs from them and upload to some github-pages dummy that would make things much easier. i was trying to clone and build the docs myself but there doesn't seem to exist any directive, also the `browser-build` file is missing and `npm run-script build` fails (`./node_modules/.bin/broccoli build dist` - for those without broccoli globally installed - fails, too). here goes the stack:

``` sh
$ ./node_modules/.bin/broccoli build dist
Error: Path or pattern "bundle.js" did not match any files
  at Object.multiGlob (/home/matters/dev/repos/pyjama/epf/node_modules/broccoli-concat/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
  at /home/matters/dev/repos/pyjama/epf/node_modules/broccoli-concat/index.js:50:30
  at $$$internal$$tryCatch (/home/matters/dev/repos/pyjama/epf/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:470:16)
  at $$$internal$$invokeCallback (/home/matters/dev/repos/pyjama/epf/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:482:17)
  at $$$internal$$publish (/home/matters/dev/repos/pyjama/epf/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:453:11)
  at $$rsvp$asap$$flush (/home/matters/dev/repos/pyjama/epf/node_modules/broccoli/node_modules/rsvp/dist/rsvp.js:1531:9)
  at process._tickCallback (node.js:419:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:906:3


Build failed
```

**Comment by fiddler** [comment]
I too was going to try out EPF and ran into same issue with the build failing!
